version: '3.8'

services:
  eksro_api:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
      - "443:443"
    depends_on:
      db:
        condition: service_healthy
    env_file:
      - ./app/.env
    volumes:
      - ./certs:/certs
      - ./uploads:/uploads
      - /etc/letsencrypt/:/etc/letsencrypt/:ro
    restart: unless-stopped

  db:
    image: postgres:15-alpine
    environment:
      POSTGRES_DB: eksro_db
      POSTGRES_USER: eksro_user
      POSTGRES_PASSWORD: 1Nju8XLZyvKdyxrdGjHuPA85Ufx5DkqY
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    restart: unless-stopped
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U eksro_user -d eksro_db"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 30s

volumes:
  postgres_data:
    driver: local
