from core.models.base import Base
from core.models.user import User
from core.models.banner import Banner
from core.models.event import Event
from core.models.feedback import Feedback
from core.models.contact import Contact
from core.models.manager import Manager
from core.models.participant import Participant
from core.models.news import News
from core.models.partner import Partner
from core.models.poll import Poll
from core.models.poll_answer import PollAnswer
from core.models.project import Project
from core.models.subscriber import Subscriber
from core.models.news_type import NewsType
from core.models.refresh_token import RefreshToken
from core.models.document import Document
from core.models.site_image import SiteImage
from core.models.about_organization import AboutOrganization
from core.models.delivered_opportunities import DeliveredOpportunity
from core.models.parent_section import (
    ParentDocument,
    ParentContact,
    ThematicMeetingParticipant,
    ThematicMeetingEvent,
    ThematicMeetingContact,
    EtiquetteInEducationDocument,
    EtiquetteInEducationEvent,
    EtiquetteInEducationContact,
    ProfessionalLearningTrajectoryDocument,
    ProfessionalLearningTrajectoryParticipant,
    ProfessionalLearningTrajectoryEvent,
    ProfessionalLearningTrajectoryContact,
)
from core.models.soviet_section import (
    SovietSupportDocument,
    SovietSupportEvent,
    SovietSupportApplication,
    SovietLeader,
    SovietNews,
    SovietQuestion,
    SovietContact,
    LearningDocument,
    LearningEvent,
    LearningApplication,
    LearningNews,
    LearningQuestion,
    LearningContact,
    OnlineConferenceRegulation,
    OnlineConferenceParticipant,
    OnlineConferenceNews,
    OnlineConferenceQuestion,
    OnlineConferenceContact,
    PodcastApplication,
    PodcastParticipant,
    PodcastNews,
    PodcastContact,
    ProjectNews,
    ProjectReport,
    CompetitionDocument,
    CompetitionContact,
    JournalNews,
    JournalContact,
)
from core.models.organization_section import (
    OrganizationSupportDocument,
    OrganizationSupportEvent,
    OrganizationSupportApplication,
    OrganizationLeader,
    OrganizationNews,
    OrganizationQuestion,
    OrganizationContact,
    OrganizationEducationalProgramDocument,
    OrganizationEducationalProgramContact,
    OrganizationThematicMeetingParticipant,
    OrganizationThematicMeetingEvent,
    OrganizationThematicMeetingContact,
    OrganizationEtiquetteInEducationDocument,
    OrganizationEtiquetteInEducationEvent,
    OrganizationEtiquetteInEducationContact,
    OrganizationProfessionalLearningTrajectoryDocument,
    OrganizationProfessionalLearningTrajectoryParticipant,
    OrganizationProfessionalLearningTrajectoryEvent,
    OrganizationProfessionalLearningTrajectoryContact,
)
from core.models.application_form import ApplicationForm


all = (
    "Base",
    "User",
    "Banner",
    "Event",
    "Feedback",
    "Contact",
    "Manager",
    "Participant",
    "News",
    "Partner",
    "Poll",
    "PollAnswer",
    "Project",
    "Document",
    "SiteImage",
    "Subscriber",
    "NewsType",
    "RefreshToken",
    "AboutOrganization",
    "DeliveredOpportunity",
    "ParentDocument",
    "ParentContact",
    "ThematicMeetingParticipant",
    "ThematicMeetingEvent",
    "ThematicMeetingContact",
    "EtiquetteInEducationDocument",
    "EtiquetteInEducationEvent",
    "EtiquetteInEducationContact",
    "ProfessionalLearningTrajectoryDocument",
    "ProfessionalLearningTrajectoryParticipant",
    "ProfessionalLearningTrajectoryEvent",
    "ProfessionalLearningTrajectoryContact",
    "SovietSupportDocument",
    "SovietSupportEvent",
    "SovietSupportApplication",
    "SovietLeader",
    "SovietNews",
    "SovietQuestion",
    "SovietContact",
    "LearningDocument",
    "LearningEvent",
    "LearningApplication",
    "LearningNews",
    "LearningQuestion",
    "LearningContact",
    "OnlineConferenceRegulation",
    "OnlineConferenceParticipant",
    "OnlineConferenceNews",
    "OnlineConferenceQuestion",
    "OnlineConferenceContact",
    "PodcastApplication",
    "PodcastParticipant",
    "PodcastNews",
    "PodcastContact",
    "ProjectNews",
    "ProjectReport",
    "CompetitionDocument",
    "CompetitionContact",
    "JournalNews",
    "JournalContact",
    "OrganizationSupportDocument",
    "OrganizationSupportEvent",
    "OrganizationSupportApplication",
    "OrganizationLeader",
    "OrganizationNews",
    "OrganizationQuestion",
    "OrganizationContact",
    "OrganizationEducationalProgramDocument",
    "OrganizationEducationalProgramContact",
    "OrganizationThematicMeetingParticipant",
    "OrganizationThematicMeetingEvent",
    "OrganizationThematicMeetingContact",
    "OrganizationEtiquetteInEducationDocument",
    "OrganizationEtiquetteInEducationEvent",
    "OrganizationEtiquetteInEducationContact",
    "OrganizationProfessionalLearningTrajectoryDocument",
    "OrganizationProfessionalLearningTrajectoryParticipant",
    "OrganizationProfessionalLearningTrajectoryEvent",
    "OrganizationProfessionalLearningTrajectoryContact",
    "ApplicationForm",
)
